# Generated by Django 3.0 on 2022-08-05 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20220805_1048'),
        ('users', '0004_auto_20220804_1515'),
    ]

    operations = [
        
    ]
