# Generated by Django 4.0.6 on 2022-07-26 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='EquipmentDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'equipment_devices',
            },
        ),
        migrations.CreateModel(
            name='EquipmentGpsTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_code', models.CharField(max_length=100, null=True)),
                ('is_power', models.BooleanField(default=False)),
                ('last_log_time', models.DateTimeField(default=datetime.date.today)),
                ('latitude', models.DecimalField(decimal_places=14, default=0.0, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=14, default=0.0, max_digits=20)),
                ('statellites_used', models.IntegerField(null=True)),
                ('battery', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_matched', models.BooleanField(default=False)),
                ('serial_number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'equipment_gps_trackers',
            },
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'errors',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'maincategories',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'status',
            },
        ),
    ]
