# Generated by Django 4.0.6 on 2022-07-29 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentgpstracker',
            name='last_log_time',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentgpstracker',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
