# Generated by Django 3.0 on 2022-08-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20220805_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentgpstracker',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
