# Generated by Django 3.0 on 2022-08-10 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20220805_1048'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='equipmentgpstracker',
            name='is_power',
            field=models.BooleanField(default=True),
        ),
       
    ]
