# Generated by Django 4.0.6 on 2022-07-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='original_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
