# Generated by Django 3.0 on 2022-08-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_auto_20220805_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='maintenance_company',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='company_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='MaintenanceCompany',
        ),
    ]
