# Generated by Django 3.0 on 2022-08-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_auto_20220808_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='maintenance',
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_manager_department',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_manager_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_manager_phone_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
    ]
