# Generated by Django 3.0 on 2022-08-09 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_auto_20220808_1250'),
    ]

    operations = [
       
    ]
