# Generated by Django 3.0 on 2022-08-09 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_auto_20220809_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='driver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='equipment.Driver'),
        ),
        migrations.DeleteModel(
            name='EquipmentDriver',
        ),
    ]
