# Generated by Django 3.0 on 2022-08-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_auto_20220809_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='is_power',
            field=models.BooleanField(default=True),
        ),
    ]
